rchw - Re-Configurable HardWare

2010, 2011, 2012 Oswald Berthold
GPL where applicable

A collection of different tools, scripts and documentation on
reconfigurable hardware (FPGAs) which was assembled or developed
as part of my diploma thesis [fn:1]. As usual this is not meant as
a canonical toolset. Rather most of the stuff in here is ad-hoc
and provided as is.

Repository: https://github.com/x75/rchw

* Modules
** dbm

Direct Bitstream Manipulation. Rapidsmith modules performing
in-place bitstream changes.

** elinux

Software intended to run on the embedded system.

*** icap-writer

modified "bitinfo" project to write bitstreams headerless to
/dev/icap

** ga-hw

Genetic algorithm with pyevolve for evolution of hardware
circuits

** genmake

generate makefiles for using the Xilinx toolchain to synthesise
single modules

** modules

various HDL sources for module implementations

** util

some utilities for working with embedded systems on Xilinx FPGAs

** vhdlparse

parse vhdl entities and generate a wrapper for use with xps,
generate tikz graphics for entity representation.

* Related

See the following items for more information
 - https://en.wikipedia.org/wiki/Reconfigurable_computing
 - Xilinx Partial Reconfiguration Documentation
 - Rapid Creation of FPGA CAD Tools for Xilinx FPGAs: http://rapidsmith.sourceforge.net/
 - Tools for Open Reconfigurable Computing: http://torc-isi.sourceforge.net/
 - Reconfigure in the Open!: http://openpr-vt.sourceforge.net/OpenPR/OpenPR.html
 - http://www2.informatik.hu-berlin.de/~oberthol/html/Hardware.html

* Footnotes
[fn:1] Self-reconfiguring System-on-Chip using Linux on a Virtex-5 FPGA
