TARGETS = read-bram-2 \
	gpio-led-blink \
	read-bram-gpio \
	softreset \
	bram2net \
	evo_binfunc \
	evo_oszillator \
	evo_oszillator_eval \
#	read-bram-1 \
#	read-bram-nosync \
#	dproc-read-bram-nosync \
#	read-debug-dsrc \
#	bit2icap \

all: $(TARGETS)

RM = rm -rf

clean:
	$(RM) $(TARGETS)	*.o *~
