-- Generated by vhdlparse 0
-- 20110825 oswald berthold
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity osc_directout_wrapper is
	Port (
		clk : in std_logic ;
		i_en : in std_logic ;
		o_osz : out std_logic ;
		o_osz_drct : out std_logic ;
		o_trig_rcnf : out std_logic
	);
end entity osc_directout_wrapper;

architecture bhv of osc_directout_wrapper is
-- Components
	component osc_directout_wrapped
		Port (
			clk : in std_logic ;
			i_en : in std_logic ;
			o_osz : out std_logic ;
			o_osz_drct : out std_logic ;
			o_trig_rcnf : out std_logic
		);
	end component;

-- signals
	signal clk_buf : std_logic ;
	signal i_en_buf : std_logic ;
	signal o_osz_buf : std_logic ;
	--signal o_osz_drct_buf : std_logic ;
	--signal o_trig_rcnf_buf : std_logic ;
-- body
begin
-- instances
	osc_directout_wrapped_inst : osc_directout_wrapped
		port map (
			clk => clk_buf,
			i_en => i_en_buf,
			o_osz => o_osz_buf,
			o_osz_drct => o_osz_drct,
			o_trig_rcnf => o_trig_rcnf
		);

-- struct/process
	buf_process: process(clk)
	begin
		if rising_edge(clk) then
			clk_buf <= clk ;
			i_en_buf <= i_en ;
			o_osz <= o_osz_buf ;
			--o_osz_drct <= o_osz_drct_buf ;
			--o_trig_rcnf <= o_trig_rcnf_buf ;
		end if;
	end process;
end bhv ;
