-- Generated by vhdlparse 0
-- 20110825 oswald berthold
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity frequency_divider_1_wrapper is
	Port (
		clk : in std_logic ;
		i_en : in std_logic ;
		o_osz : out std_logic
	);
end entity frequency_divider_1_wrapper;

architecture bhv of frequency_divider_1_wrapper is
-- Components
	component frequency_divider_1_wrapped
		Port (
			clk : in std_logic ;
			i_en : in std_logic ;
			o_osz : out std_logic
		);
	end component;

-- signals
	signal clk_buf : std_logic ;
	signal i_en_buf : std_logic ;
	signal o_osz_buf : std_logic ;
-- body
begin
-- instances
	frequency_divider_1_wrapped_inst : frequency_divider_1_wrapped
		port map (
			clk => clk_buf,
			i_en => i_en_buf,
			o_osz => o_osz_buf
		);

-- struct/process
	buf_process: process(clk)
	begin
		if rising_edge(clk) then
			clk_buf <= clk ;
			i_en_buf <= i_en ;
			o_osz <= o_osz_buf ;
		end if;
	end process;
end bhv ;
