-- File: simple_adder.vhd
-- Generated by MyHDL 0.7
-- Date: Thu Apr 14 11:51:55 2011


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_07.all;

entity simple_adder is
    port (
        a: in unsigned(7 downto 0);
        b: in unsigned(7 downto 0);
        c: out unsigned(8 downto 0);
        clk: in std_logic
    );
end entity simple_adder;


architecture MyHDL of simple_adder is


begin




SIMPLE_ADDER_ADDITION: process (clk) is
begin
    if rising_edge(clk) then
        c <= (resize(a, 9) + b);
    end if;
end process SIMPLE_ADDER_ADDITION;

end architecture MyHDL;
